"""add NUS reference data

Revision ID: 88c136cec2e9
Revises: 7eec0fe94b3d
Create Date: 2026-10-08 18:59:43.650503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c136cec2e9'
down_revision: Union[str, Sequence[str], None] = '7eec0fe94b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculties',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index('ix_faculties_name_trgm', 'faculties', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('modules',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('faculty', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('ix_modules_code_prefix', 'modules', ['code'], unique=False, postgresql_ops={'code': 'varchar_pattern_ops'})
    op.create_index('ix_modules_title_trgm', 'modules', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('departments',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('faculty', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['faculty'], ['faculties.name'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index('ix_departments_name_trgm', 'departments', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_departments_name_trgm', table_name='departments', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('departments')
    op.drop_index('ix_modules_title_trgm', table_name='modules', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_modules_code_prefix', table_name='modules', postgresql_ops={'code': 'varchar_pattern_ops'})
    op.drop_table('modules')
    op.drop_index('ix_faculties_name_trgm', table_name='faculties', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('faculties')
    # ### end Alembic commands ###
