"""add semester to reviews

Revision ID: 9a4acaf001b8
Revises: 88c136cec2e9
Create Date: 2026-10-08 19:40:51.365815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4acaf001b8'
down_revision: Union[str, Sequence[str], None] = '88c136cec2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deleted_reviews', sa.Column('academic_year', sa.SmallInteger(), nullable=True))
    op.add_column('deleted_reviews', sa.Column('semester', sa.SmallInteger(), nullable=True))
    op.add_column('reviews', sa.Column('academic_year', sa.SmallInteger(), nullable=True))
    op.add_column('reviews', sa.Column('semester', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###
    # CHECK constraints on an existing table aren't detected by autogenerate
    op.create_check_constraint('ck_reviews_semester_range', 'reviews', 'semester BETWEEN 1 AND 4')
    op.create_check_constraint(
        'ck_reviews_term_complete', 'reviews', '(academic_year IS NULL) = (semester IS NULL)'
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_reviews_term_complete', 'reviews', type_='check')
    op.drop_constraint('ck_reviews_semester_range', 'reviews', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'semester')
    op.drop_column('reviews', 'academic_year')
    op.drop_column('deleted_reviews', 'semester')
    op.drop_column('deleted_reviews', 'academic_year')
    # ### end Alembic commands ###
