"""add staff directory

Revision ID: a9559675428a
Revises: 1262e8c7c2d9
Create Date: 2026-10-08 21:32:47.128265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9559675428a'
down_revision: Union[str, Sequence[str], None] = '1262e8c7c2d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_directory',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=120), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('section', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('faculty', sa.String(length=120), nullable=True),
    sa.Column('research_areas', sa.Text(), nullable=True),
    sa.Column('profile_urls', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_staff_directory_name_key_trgm', 'staff_directory', ['name_key'], unique=False, postgresql_using='gin', postgresql_ops={'name_key': 'gin_trgm_ops'})
    op.create_index('ix_staff_directory_name_trgm', 'staff_directory', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('uq_staff_directory_source_name', 'staff_directory', ['source_url', 'name_key'], unique=True)
    op.add_column('professors', sa.Column('staff_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint('professors_staff_id_key', 'professors', ['staff_id'])
    op.create_foreign_key('professors_staff_id_fkey', 'professors', 'staff_directory', ['staff_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('professors_staff_id_fkey', 'professors', type_='foreignkey')
    op.drop_constraint('professors_staff_id_key', 'professors', type_='unique')
    op.drop_column('professors', 'staff_id')
    op.drop_index('uq_staff_directory_source_name', table_name='staff_directory')
    op.drop_index('ix_staff_directory_name_trgm', table_name='staff_directory', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_staff_directory_name_key_trgm', table_name='staff_directory', postgresql_using='gin', postgresql_ops={'name_key': 'gin_trgm_ops'})
    op.drop_table('staff_directory')
    # ### end Alembic commands ###
